### ISSUE TITLE
Add support for GNOME 40

### ISSUE THREAD

**Issue by lozanotux** [Edenhofer/Minimalism-Gnome-Shell#13]
Hi, I have been using this extension on my productive laptop in my work. Is it possible to update this extension to add support for gnome 40? I'm a Fedora user
![hw_issue_g40](https://user-images.githubusercontent.com/6494902/118558201-accd7980-b73c-11eb-9351-62bd977aead4.png)

**Comment by Edenhofer** [comment]
I bumped the version in hopes that the API hasn't changed too much. If it is not working, please feel free to reopen this ticket.

**Comment by Edenhofer** [comment]
Ah sorry, I now see the problem. Gnome has drastically changed its workspace layout. Sorry, this extension wouldn't work anymore.
I switched to a tiling window manager recently and don't have the time to continue developing this extensions especially because I don't have an easy way to test changes anymore. Having said that, I would be more than happy though to review and incorporate merge request!
