### ISSUE TITLE
Hide dash X does not work after latest upgrade to 3.36

### ISSUE THREAD

**Issue by iago-lito** [Edenhofer/Minimalism-Gnome-Shell#9]
I get no result from activating the `Hide Dash X` extension since latest upgrade to gnome 3.36 on Arch. Even after a fresh reinstall of the extension, and even if every other extension is disabled. Is something broken with 3.36? :'(

```
$ uname -a
Linux etak 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64 GNU/Linux

$ gnome-shell --version
GNOME Shell 3.36.0
```

**Comment by Edenhofer** [comment]
I am extremely busy due to my academic projects at the moment and can not spare the time to update the code of the extension. I am sorry about that!

However, I encourage you to check out the code and look into how the couple of javascript lines in  the [extensions](https://github.com/Edenhofer/Minimalism-Gnome-Shell/blob/master/hide-dash%40xenatt.github.com/extension.js) need to be adapted to make it work with gnome 3.36. It might involve some digging through gnome documentation and would probably eat up some time finding the right hook but it should be quite simple in principle. I am more than happy to incorporate any findings you might unveil.

**Comment by Edenhofer** [comment]
Thanks @lfom for the patch!
